"""chaged enum value

Revision ID: 4637bfa354f3
Revises: 832966c29709
Create Date: 2021-12-02 14:45:37.242193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4637bfa354f3'
down_revision = '832966c29709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
