"""Added customers table

Revision ID: 832966c29709
Revises: 7f427faac4d3
Create Date: 2021-12-02 13:26:48.997054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832966c29709'
down_revision = '7f427faac4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=14), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=False),
    sa.Column('blood_group', sa.Enum('a_positive', 'a_negative', 'b_positive', 'b_negative', 'o_positive', 'o_negative', 'ab_positive', 'ab_negative', name='bloodgroupenum'), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
